[package]
name = "king"
version = "0.1.0"
authors = ["Juan Ibiapina <juanibiapina@gmail.com>"]

[dependencies]
ncurses = "*"
unicode-width = "*"
unicode-segmentation = "*"
libc = "*"

[[bin]]
name = "king"
doc = false
