[package]
name = "king"
version = "0.1.0"
authors = ["Juan Ibiapina <juanibiapina@gmail.com>"]

[dependencies]
unicode-width = "*"
unicode-segmentation = "*"
libc = "*"

[dependencies.ncurses]
version = "*"
features = ["wide"]

[[bin]]
name = "king"
doc = false
